php:
  preset: laravel

  # https://docs.styleci.io/standalone-php#risky
  risky: false

  enabled:
    # - single_quote
    # - phpdoc_summary

  disabled:
    # - self_accessor

  finder:
    exclude:
      - "docs"
      - "public"
      - "resources"
    name:
      - "*.php"
    not-name:
      - "*blade.php"
js:
  finder:
    not-name:
      - webpack.mix.js

css: true
