# Travis CI Build Config Explorer
# https://config.travis-ci.com/explore

language: php
os:
  - linux
dist: xenial

# https://docs.travis-ci.com/user/notifications
notifications:
  email:
    on_success: never
    on_failure: never

jobs:
  include:

    # https://docs.travis-ci.com/user/deployment/pages
    - stage: deploy
      if: branch = master
      name: Source Code Docs
      php: '7.2'
      install:
      - curl -O http://get.sensiolabs.org/sami.phar
      script:
      - php sami.phar update .sami
      deploy:
      - provider: pages
        local_dir: docs
        on:
          branch: master
        skip-cleanup: true
        token: "$GITHUB_TOKEN"
